### ISSUE TITLE
The files are not downloaded to Google Drive folder even if the "Save files to Google Drive" option is set

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#14]
[Notes]:
- Before setting the "Save to Google Drive" option,if a downloaded file was moved to Google Drive from context menu option, the issue is no longer reproducible.

[Affected versions]:
- Nightly 61.0a1

[Affected Platforms]:
- Windows 7 x64
- Windows 10 x64
- Mac 10.13

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Google Drive Storage installed on the computer: https://www.google.com/drive/download/. 
- Have the CloudStorage add-on installed.

[Steps to reproduce]:
1. Start the Nightly browser with the profile from prerequisites and navigate to https://www.mozilla.org/en-US/firefox/all/ page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar.
5. Click the "Save to Google Drive" option.
6. Navigate again to https://www.mozilla.org/en-US/firefox/all/  and download another file.
7. Observe the folder where the file was downloaded.

[Expected result]:
- The file is downloaded to Google Drive folder.

[Actual result]:
- The file is downloaded to local download folder.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/mmTCgq

**Comment by punamdahiya** [comment]
From screen recording, it seems 'Save to Google Drive' button click in notification didn't go through.  It should have set pref 'cloud.services.storage.key' to GDrive, is that reflected?
 Is there any error in browser console?

I have tried to replicate the issue but failed. Looks like I have a different build as I pushed some changes today. Can you please try if this issue replicates with latest commits. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have created today a new custom build from cloud-storage-web-ext branch and I can still reproduce the issue on latest Nightly build.
It seems that the "cloud.services.storage.key" is correctly set to "GDrive", but the files are not downloaded there.
Here is a screenshot with browser console errors that appears after downloading a file, but I am not sure if the error is related to Cloud Storage:
![image](https://user-images.githubusercontent.com/19226534/38799554-6facdfd4-416d-11e8-9ebf-5921211b763a.png)

As I mentioned in the issue,  if a downloaded file was moved to Google Drive from context menu option, the issue is no longer reproducible.
So probably if you previously downloaded a file in Google Drive folder, Firefox recognize the path and the issue is no longer reproducible.

**Comment by SoftVision-CosminMuntean** [comment]
After further investigations, I have noticed that the "Downloads" folder is not automatically created when Google Drive is installed. It seems that the issue is reproducible when the "Downloads" folder is not created.

The same issue is also reproducible for Dropbox, if the "Downloads" folder is not created or was previously deleted.

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean +1, I will submit the fix. Thanks for helping nail down the cause!

**Comment by punamdahiya** [comment]
PR updated with fix, leaving issue open for QA to verify

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest CloudStorage add-on installed (v1.0.0-04.17.2018), tested this on Windows 10 x64 and Mac 10.13 with the latest Nightly(61.0a1-20180416220315).

**Comment by punamdahiya** [comment]
Thanks @SoftVision-EmilPasca , marking issue closed
